### ISSUE TITLE
Make slide up overlay brighter

### ISSUE THREAD

**Issue by cmcfadden** [UMN-LATIS/camino-trekker#10]
Right now, it's a little too dingy. Maybe make the opacity like 0.9 instead of 0.5?

**Comment by jxjj** [comment]
a smidge higher opacity. Not too much though: without it, the sheet just looked light a solid color, and you lost the glassmorphic effect. Instead removed the dark backdrop and replaced with a light box-shadow to give bg a slightly darker treatment and the sheet a subtle border.

<img width="474" alt="Screen Shot 2022-03-25 at 1 58 25 PM" src="https://user-images.githubusercontent.com/980170/160184684-8c38606c-0a00-4030-9fae-73cb561facde.png">
