### ISSUE TITLE
Add a "max-height" on images?

### ISSUE THREAD

**Issue by cmcfadden** [UMN-LATIS/camino-trekker#11]
Right now on larger displays, images can extend past the window height. Maybe cap max-height at 80vh-ish?

**Comment by jxjj** [comment]
In the lightbox view or gallery? (or someplace else)

**Comment by cmcfadden** [comment]
gallery.
<img width="1418" alt="Screen Shot 2022-03-25 at 2 38 27 PM" src="https://user-images.githubusercontent.com/211655/160189930-991eb307-2bcb-4596-91c4-9615422d07b4.png">

**Comment by jxjj** [comment]
Resolved with https://github.com/UMN-LATIS/camino-trekker/commit/4bf2c66f1dfe105b76bd59ac9e881ded26afe2f9
