### ISSUE TITLE
Occasionally "show map" navigates to the next stop

### ISSUE THREAD

**Issue by cmcfadden** [UMN-LATIS/camino-trekker#9]
Haven't quite figured out what combination of state does this. Some combination of jumping between stops with the bottom bar and showing/hiding the map occasionally causes the app to navigate to the next stop instead of opening the map when the "Show map" button is pressed.

**Comment by jxjj** [comment]
Do you experience this on phone or laptop or both?

**Comment by cmcfadden** [comment]
only on the laptop so far

**Comment by jxjj** [comment]
I _think_ this is fixed after removing swiper. LMK if you run into again!

Current version: https://umn-latis.github.io/camino-trekker/tours/6/stops/0
